engines:
  duplication:
  	enabled: false
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
   	enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
